# Generated by Django 3.0 on 2020-05-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='time_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
