# Generated by Django 3.0 on 2020-05-08 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.OneToOneField(max_length=30, on_delete=django.db.models.deletion.CASCADE, related_name='f_name', to=settings.AUTH_USER_MODEL)),
                ('last_name', models.OneToOneField(max_length=30, on_delete=django.db.models.deletion.CASCADE, related_name='l_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
